url: "https://BaiYunpeng1949.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: " " # the subpath of your site, e.g. /blog
title: "Bai Yunpeng (白云鹏)" # the name of your site, e.g. ACME Corp.
description: "Chinese, PhD Candidate at NUS"
theme: academic-jekyll-theme
