menu:
#- {name: 'people', url: '/people'}
- {name: 'Home', url: '/index'}
# - {name: 'Publications', url: '/publications'}
#- {name: 'courses', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/BaiYunpeng1949'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/%E4%BA%91%E9%B9%8F-%E7%99%BD-92aa27191/'}
- {icon: 'google scholar', link: 'https://scholar.google.com/citations?user=rpliY_AAAAAJ&hl=en&oi=ao'}

contacts:
- {
  name: 'Bai Yunpeng (白云鹏)', title: 'PhD Student', department: 'Computer Science', institution: 'National University of Singapore', institution_address: '21 Lower Kent Ridge Rd, Singapore 119077', phone: '(+65) 8941-9601', email: 'bai_yunpeng99@u.nus.edu', office: 'Innovation 4.0 #5',
  image: 'assets/img/contact.jpg',
}
